Lionel794
mernxl/premier-dev-socialbook-api pull request #4
Opened 2021-08-23 16:44 UTC by spykelion

# Modification

- [ ] fix bug find user by id
- [ ] Break application into modules

2021-08-25 14:22 UTC, mernxl requested changes

2021-08-25 14:22 UTC, mernxl commented on src/index.js
> +app.use('/users/:id', userRouter);
You don't need this here, since you already have it at /users route.

also, this line will mount the userRouter on users/id which will not be reached since it's implemented by userRouter on /users

2021-08-25 14:22 UTC, mernxl commented on src/index.js
> +app.use('/posts/:id', postRouter);
Same comments as /users/:id route

2021-08-25 14:23 UTC, mernxl commented
Update your code to remove conflicts.

2021-08-25 17:11 UTC, spykelionel commented
ok sir

On Wed, Aug 25, 2021, 3:23 PM Rodrick Nfinyoh M ***@***.***>
wrote:

> Update your code to remove conflicts.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mernxl/premier-dev-socialbook-api/pull/4#issuecomment-905546336>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AODRKCDAZXVCYFHP37KXKDTT6T4F3ANCNFSM5CU63FSA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-30 11:09 UTC, spykelion commented
> Update your code to remove conflicts.

Conflicts resolved.

- [ ] Able to merge

2021-08-30 11:10 UTC, spykelion commented
Changes made and conflicts resovled

2021-10-02 22:41 UTC, mernxl commented
Hi @spykelion i will review by next week end. ✌️. 
Nice of you to continue work.

2021-10-03 05:13 UTC, spykelion commented
Great, thanks!

On Sat, Oct 2, 2021, 11:42 PM Rodrick Nfinyoh M ***@***.***>
wrote:

> Hi @spykelion <https://github.com/spykelion> i will review by next week
> end. ✌️.
> Nice of you to continue work.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mernxl/premier-dev-socialbook-api/pull/4#issuecomment-932829638>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AODRKCGW6U5UT23CAAZYCHDUE6DDTANCNFSM5CU63FSA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2024-09-26 17:36 UTC, closed without merging